### ISSUE TITLE
Namespace questions

### ISSUE THREAD

**Issue by coderanger** [EmbarkStudios/k8s-buildkite-plugin#15]
This whole plugin appears to expect that buildkite is running in the default namespace? Is there a reason for that?

**Comment by iffyio** [comment]
Hi @coderanger Did you have a particular example of this in mind?
Generally the plugin assumes it's being run in kubernetes and relies on `kubectl` to detect that it's running inside a kubernetes cluster and talk to the cluster's apiserver to get context. The default behavior is that `kubectl` commands are applied on the namespace of the pod that runs it - in this case the namespace of the buildkite agent - that's where e.g jobs will be created

**Comment by coderanger** [comment]
I think my issue is actually RBAC, not the namespace of the jobs :) Sorry for the noise, going to close this but will hopefully be able to contribute an RBAC policy example.
