### ISSUE TITLE
Logs not streamed to Buildkite and Jobs are not cleaned up 

### ISSUE THREAD

**Issue by mpalu** [EmbarkStudios/k8s-buildkite-plugin#24]
Hello, 

Any thoughts on why the execution output is not appearing in Buildkite UI although it appears in the pod logs? I'm not receiving any error or exception what difficult troubleshoot.

Besides that, at the end of the execution, I can see the message the job is patched, but they aren't automatically deleted even after some days.

![image](https://user-images.githubusercontent.com/72210801/114928955-95cbfc80-9e09-11eb-9572-822d7ddb7764.png)

Using version EmbarkStudios/k8s#1.2.8

**Comment by iffyio** [comment]
Hi! I think the logs not being shown is likely an issue introduced with the latest version 1.2.9. And yes jobs should be automatically deleted by default theres a function for that here https://github.com/EmbarkStudios/k8s-buildkite-plugin/blob/HEAD/hooks/command#L38-L47 maybe its not doing what is expected.

I'll try to have a look at them when I get some time but if in the meantime anyone would like to tackle this do go for it!

**Comment by mpalu** [comment]
Hi, @iffyio thanks for the reply.  I don't think it was introduced with that version because I tested with versions from 1.2.6 to 1.2.9 and got the same behavior with all of them.

**Comment by mpalu** [comment]
<s>One more update, with version 1.2.9 the bootstrap container isn't passing the complete status to Buildkite, so besides the container is Complete, the bootstrap still shown as running on Buildkite. Only happens with the 1.2.9 version.</s>

<s>Edit: believe it's missing an `&` signal at the end of the command here https://github.com/EmbarkStudios/k8s-buildkite-plugin/blob/master/hooks/command#L149</s>

After solving the logs issue the bootstrap part worked as expected.

**Comment by mpalu** [comment]
According to the following messages, I need to set `--feature-gates=TTLAfterFinished=true` on my cluster to get it able to cleanup the jobs.

https://github.com/kubernetes/kubernetes/issues/71993#issuecomment-446939614

https://stackoverflow.com/questions/60582829/how-to-enable-ttlafterfinished-true-in-the-kubernetes-cluster

**Comment by mpalu** [comment]
I got the logs by adding a `pod/log` RBAC verbs, so I think we are good. It was a problem with my implementation and not with the plugin.

**Comment by iffyio** [comment]
Glad you found the cause of the logs issue! :+1:
