### ISSUE TITLE
Assign Embark maintainer to CODEOWNERS

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/k8s-buildkite-plugin#50]
We need find a new maintainer for this project and update `./CODEOWNERS` to point to that, to prevent our OSS-checker tool from complaining on Slack about not having that assigned to an Embark maintainer every day.

@vojd or @Jake-Shadle have anyone in your team we can assign for that? Would be very minimal work, as not much new stuff happening in this repro but need officially have a maintainer.

**Comment by Jake-Shadle** [comment]
We have never used this project and I have no idea if anyone else does. If they don't we should just archive it.

**Comment by repi** [comment]
Oh :) If that is indeed the case and no projects at Embark are using it (anymore), then yes then archiving it sounds like a plan

**Comment by keith** [comment]
We're heavily using this project at Lyft, but I guess the suggestion for us if you choose to archive would be for us to start maintaining a new fork?

**Comment by repi** [comment]
@keith cool to hear! and thanks for letting us know.

if we at Embark indeed do not use or maintain this, another option (if you are open for it) would be for us to simply transfer the repository and ownership of it to your org? Would be nice to find a new home for it rather than archiving!

**Comment by keith** [comment]
I'd have to work with some folks on something like that, when will you know what your plans are for it?

**Comment by repi** [comment]
No worries, understandable, we'll figure out this week what the future of this repo is from our perspective. And if we do not use it we likely do not immediately need to archive it if you are still discussing internally - but figuring out a path in the next 2-3 weeks would be good I think

**Comment by keith** [comment]
I'll wait to hear on that before bringing it up here then

**Comment by tgolsson** [comment]
Hey @keith! 

We've had some internal discussion and since I'm the primary internal user for this project; I'm stepping up as maintainer. However; given your history of contributions to the project, and the usage at Lyft; I'd be happy to have you on-board as co-maintainer if you'd be interested in that.

**Comment by keith** [comment]
Glad to hear it! I'd be happy to help!

**Comment by repi** [comment]
@keith that's awesome!

@tgolsson I think you can add @keith then to `./CODEOWNERS` and you'll both get the reviews for PRs to the repo.

You would also have to add him to this file so our slackbot doesn't complain about it: https://github.com/EmbarkStudios/opensource/blob/main/src/policy.rs
